app_home/urls.py
from django.urls import path
from . import views

app_name = "app_home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path(
        "developers/",
        views.DeveloperOverview.as_view(),
        name="developer-overview",
    ),
    path(
        "projects/", views.ProjectOverview.as_view(), name="project-overview"
    ),
    path(
        "projects/create/",
        views.CreateProjectView.as_view(),
        name="create-project",
    ),
    path(
        "users/<int:pk>/",
        views.ProfileDetailView.as_view(),
        name="profile-detail-view",
    ),
    path(
        "projects/<int:pk>/",
        views.ProjectDetailView.as_view(),
        name="project-detail-view",
    ),
    path(
        "projects/edit/<int:pk>/",
        views.EditProjectView.as_view(),
        name="project-edit-view",
    ),
    path(
        "projects/delete/<int:pk>/",
        views.DeleteProjectView.as_view(),
        name="delete-project",
    ),
    path(
        "projects/<int:pk>/picture/",
        views.AddProjectPicture.as_view(),
        name="add-project-pic",
    ),
    path(
        "projects/picture/delete/<int:pk>/",
        views.DeleteProjectPicture.as_view(),
        name="delete-project-pic",
    ),
]

app_user/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "app_user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path(
        "profile/edit/", views.EditProfileView.as_view(), name="edit-profile"
    ),
    path(
        "profile/delete/",
        views.DeleteProfileView.as_view(),
        name="delete-profile",
    ),
    path(
        "profile/picture/",
        views.AddProfilePicView.as_view(),
        name="add-profile-pic",
    ),
    path(
        "profile/picture/delete/<int:pk>/",
        views.DeleteProfilePicView.as_view(),
        name="delete-profile-pic",
    ),
    path("messages/", views.Messages.as_view(), name="messages"),
    path("messages/sent/", views.SentMessages.as_view(), name="sent-messages"),
    path(
        "messages/<int:pk>/",
        views.IndividualMsg.as_view(),
        name="individual_msg",
    ),
    path(
        "messages/send/<int:pk>/",
        views.AddMessage.as_view(),
        name="add_message",
    ),
    path(
        "messages/edit/<int:pk>/",
        views.EditMessage.as_view(),
        name="edit_message",
    ),
    path(
        "messages/delete/<int:pk>/",
        views.DeleteMessage.as_view(),
        name="delete_message",
    ),
]

developer_matcher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", include("app_home.urls")),
    path("user/", include("allauth.urls")),
    path("user/", include("app_user.urls")),
]

app_home/models.py
from django.db import models

# Create your models here.

app_home/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from app_user.models import Project, ProjectPicture, User
from django.contrib import messages
from better_profanity import profanity


def validate_project_name(data):
    """
    Checks that a project name is not already taken and does not
    contain profanities
    """

    if isinstance(data, str):
        project_name = data
    else:
        project_name = data.cleaned_data.get("title", None)
        if not project_name:
            raise ValidationError("No title given")
        else:
            if data.instance:
                if data.instance.title == project_name:
                    return

    # Check project name for profanity and do not allow if present
    if profanity.contains_profanity(project_name):
        raise ValidationError("profanity")
    else:
        # Check if project name already taken and return error if so
        try:
            taken_project_name = Project.objects.get(title=project_name)
            raise ValidationError("duplicate_name")
        except Project.DoesNotExist:
            return


class ProjectCreationForm(forms.ModelForm):
    """
    Form for creation of new projects
    """

    class Meta:
        model = Project
        fields = ["p_language", "title", "description"]
        labels = {
            "p_language": "Programming Language(s)",
        }

    def save(self, commit=True):
        project = super(ProjectCreationForm, self).save(commit=False)
        if commit:
            project.save()
        return project

    def clean(self):
        """
        Calls the validate_project_name method to check for
        duplicates and profanities
        """
        validate_project_name(self)


class ProjectEditForm(forms.ModelForm):
    """
    Form to edit existing projects
    """

    class Meta:
        model = Project
        fields = ["p_language", "title", "description"]
        labels = {
            "p_language": "Programming Language(s)",
        }

    def save(self, commit=True):
        project = super(ProjectEditForm, self).save(commit=False)
        if commit:
            project.save()
        return project

    def clean(self):
        """
        Calls the validate_project_name method to check for
        duplicates and profanities
        """
        validate_project_name(self)


class AddProjectPictureForm(forms.ModelForm):
    """
    Form for adding a new picture to a project
    """

    class Meta:
        model = ProjectPicture
        fields = "__all__"
        exclude = ["project"]
        labels = {"project_picture": "Project picture"}


class UserLangSelectFilterForm(forms.ModelForm):
    """
    Form to obtain the programming language of interest from the list of
    all languages
    """

    class Meta:
        model = User
        fields = ["p_language"]
        labels = {"p_language": "Filter users by programming language(s)"}
        widgets = {
            "p_language": forms.SelectMultiple(attrs={"class": "p-lang-form"})
        }


class ProjectLangSelectFilterForm(forms.ModelForm):
    """
    Form to obtain the programming language of interest from the list of
    all languages
    """

    class Meta:
        model = Project
        fields = ["p_language"]
        labels = {"p_language": "Filter projects by programming language(s)"}
        widgets = {
            "p_language": forms.SelectMultiple(attrs={"class": "p-lang-form"})
        }

app_home/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import TemplateView, FormView
from app_user.models import User, Project, ProgramLang, ProjectPicture
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
import random
from .forms import (
    ProjectCreationForm,
    ProjectEditForm,
    AddProjectPictureForm,
    UserLangSelectFilterForm,
    ProjectLangSelectFilterForm,
)


class HomeView(TemplateView):
    """
    View for the home page.
    """

    model = User
    template_name = "app_home/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AboutView(TemplateView):
    """
    View for the about page.
    """

    model = User
    template_name = "app_home/about.html"


class DeveloperOverview(TemplateView):
    """
    View for the general overview displaying all users except the
    logged in user.
    """

    model = User
    template_name = "app_home/developer_overview.html"

    def get(self, request, *args, **kwargs):
        if request.GET.get("p_language", None):
            p_langs = ProgramLang.objects.filter(
                pk__in=request.GET.getlist("p_language")
            )
        else:
            p_langs = []
        form = UserLangSelectFilterForm(initial={"p_language": p_langs})

        all_users = User.objects.all().exclude(pk=request.user.pk)
        href_filter = ""
        for lang in p_langs:
            all_users = all_users.filter(p_language=lang).order_by("id")
            href_filter += f"&p_language={lang.pk}"

        # set up pagination for users (8 per page)
        # passing in users filtered by p_lang that are distinct
        paginator = Paginator(all_users, 8)
        page_number = request.GET.get("page")
        users = paginator.get_page(page_number)
        p_nums = "p" * users.paginator.num_pages
        context = {
            "form": form,
            "href_filter": href_filter,
            "users": users,
            "p_nums": p_nums,
        }
        return render(request, "app_home/developer_overview.html", context)


class ProfileDetailView(LoginRequiredMixin, TemplateView):
    """
    View for rendering detailed profile view for chosen user.
    """

    model = User
    template_name = "app_home/user_detail_view.html"

    def get(self, request, *args, **kwargs):
        profile_pk = kwargs["pk"]
        user_to_get = get_object_or_404(User, pk=profile_pk)
        try:
            user_to_get_projects = Project.objects.filter(user=user_to_get)
        except Exception:
            user_to_get_projects = None

        try:
            p_langs = user_to_get.p_language.values()
        except Exception:
            p_langs = None

        context = {
            "user": request.user,
            "user_for_profile": user_to_get,
            "p_langs": p_langs,
            "user_projects": user_to_get_projects,
        }
        return render(request, "app_home/user_detail_view.html", context)


class ProjectOverview(TemplateView):
    """
    Project overview view.
    """

    model = Project
    template_name = "app_home/project_overview.html"

    def get(self, request, *args, **kwargs):
        if request.GET.get("p_language", None):
            p_langs = ProgramLang.objects.filter(
                pk__in=request.GET.getlist("p_language")
            )
        else:
            p_langs = []
        form = ProjectLangSelectFilterForm(initial={"p_language": p_langs})

        all_projects = Project.objects.all()
        href_filter = ""
        for lang in p_langs:
            all_projects = all_projects.filter(p_language=lang).order_by("id")
            href_filter += f"&p_language={lang.pk}"

        # set up pagination
        paginator = Paginator(all_projects, 4)
        page_number = request.GET.get("page")
        projects = paginator.get_page(page_number)
        p_nums = "p" * projects.paginator.num_pages
        context = {
            "form": form,
            "href_filter": href_filter,
            "projects": projects,
            "p_nums": p_nums,
        }
        return render(request, "app_home/project_overview.html", context)


class ProjectDetailView(LoginRequiredMixin, TemplateView):
    """
    View for rendering the detail page for a project.
    """

    model = Project
    template_name = "app_home/project_detail_view.html"

    def get(self, request, *args, **kwargs):
        project_pk = kwargs["pk"]
        project_to_get = get_object_or_404(Project, pk=project_pk)

        context = {"user": request.user, "project": project_to_get}

        return render(request, "app_home/project_detail_view.html", context)


class CreateProjectView(LoginRequiredMixin, FormView):
    """
    View to create a project.
    """

    template_name = "app_home/create_project.html"
    form_class = ProjectCreationForm

    def get(self, request):
        project_form = ProjectCreationForm()
        context = {"form": project_form}

        return render(request, "app_home/create_project.html", context)

    def post(self, request):
        user = request.user
        form = self.form_class(request.POST)
        p_langs = form.data.getlist("p_language")

        if form.is_valid():
            new_project = form.save()
            new_project.user.add(user)
            for lang in p_langs:
                new_project.p_language.add(lang)
                new_project.save()
            messages.success(request, "Project successfully created!")
            return redirect(
                reverse(
                    "app_home:project-detail-view",
                    kwargs={"pk": new_project.pk},
                )
            )
        elif "profanity" in form.errors.as_text():
            messages.error(
                request, "Please do not use profanities in your project name!"
            )
        elif "duplicate_name" in form.errors.as_text():
            messages.error(
                request, "Project name already taken! Please choose another."
            )
        else:
            messages.error(
                request, "Please select at least one programming language"
            )
        return redirect(reverse("app_home:create-project"))


class EditProjectView(LoginRequiredMixin, TemplateView):
    """
    View to edit a project
    """

    model = Project
    template_name = "app_home/edit_project.html"

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs["pk"])
        if project.user.get() != request.user:
            return redirect("app_home:project-overview")
        else:
            context = {
                "project": project,
                "form": ProjectEditForm(instance=project),
            }

        return render(request, "app_home/edit_project.html", context)

    def post(self, request, *args, **kwargs):
        user = request.user
        project = get_object_or_404(Project, pk=kwargs["pk"])
        form = ProjectEditForm(request.POST, instance=project)
        p_langs = form.data.getlist("p_language")
        if form.is_valid():
            project = form.save(commit=False)
            project.p_language.set(p_langs)
            project.save()
            messages.success(request, "Project successfully edited!")
            return redirect(
                reverse(
                    "app_home:project-detail-view", kwargs={"pk": project.pk}
                )
            )
        elif "profanity" in form.errors.as_text():
            messages.error(
                request, "Please do not use profanities in your project name!"
            )
            return render(
                request, "app_home/edit_project.html", {"form": form}
            )
        elif "duplicate_name" in form.errors.as_text():
            messages.error(
                request, "Project name already in use! Please choose another"
            )
            return render(
                request, "app_home/edit_project.html", {"form": form}
            )
        elif not form["p_language"].value():
            messages.error(
                request, "Please select at least one programming language"
            )
        else:
            messages.error(
                request, "Form could not be submitted. Please try again"
            )
        return render(request, "app_home/edit_project.html", {"form": form})


class DeleteProjectView(LoginRequiredMixin, TemplateView):
    """
    View to delete a project
    """

    model = Project
    template_name = "app_home/about.html"

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs["pk"])
        if project:
            if project.user.get() != request.user:
                return redirect("app_home:project-overview")
            else:
                project.delete()
                messages.success(request, "Project successfully deleted!")
        else:
            messages.error(
                request, "Project could not be deleted. Please try again."
            )
        return redirect(reverse("app_home:project-overview"))


class AddProjectPicture(LoginRequiredMixin, TemplateView):
    """
    View to add a picture to a project
    """

    model = ProjectPicture
    template_name = "app_home/project_picture.html"

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs["pk"])
        if project.project_pic:
            pic_query_set = project.project_pic.values()
        else:
            pic_query_set = [""]
        form = AddProjectPictureForm()
        context = {
            "project": project,
            "pictures": pic_query_set,
            "form": form,
        }
        return render(request, "app_home/project_picture.html", context)

    def post(self, request, *args, **kwargs):

app_home/templates/app_home/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2 text-center">
            <h1>About</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 offset-md-2 text-center">
            <p>
                Welcome to Developer Connect!
            </p>
            <p>
                The site was developed with the purpose to link up developers with one another so that they can connect with one another and develop and work on ideas together.
            </p>
            <p>
                Please select an option below to get started!
            </p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12 text-center">
    {% if user.is_authenticated %}
        <a href="{% url 'app_home:developer-overview' %}" class="btn btn-primary small-margin-top small-margin-top">Developer Overview</a>
        <a href="{% url 'app_home:project-overview' %}" class="btn btn-primary small-margin-top">Project Overview</a>
    {% else %}
        <a href="{% url 'app_user:register' %}" class="btn btn-primary small-margin-top">Register</a>
        <a href="/user/login/" class="btn btn-primary small-margin-top">Login</a>
    {% endif%}
        </div>
    </div>

</div>



{% endblock %}

app_home/templates/app_home/create_project.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Create Project{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h1>Create New Project</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <a href="{% url 'app_home:project-overview' %}" class="btn btn-danger">Cancel</a>
                <button class="btn btn-primary">Create Project</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_home/templates/app_home/developer_overview.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Developers{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Developer Overview</h1>
        </div>
    </div>

    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-md-8">
                <form method="GET">
                    {{ form|crispy }}
                    <button class="btn btn-primary small-margin">Submit</button>
                </form>
        </div>
    </div>

    <div class="row gy-3">
        {% for dev in users %}
            {% if dev != user and dev != admin %}
                <div class="col-md-6 col-lg-3">
                    <div class="card text-center card-title h-100 gap-betwen-cards">
                        <a href="{% url 'app_home:profile-detail-view' dev.pk %}">
                            {% if dev.profile_pic.values %}
                            <img src="{{ dev.profile_pic.values.0.profile_picture.url }}" alt="{{ dev.username }}'s profile picture" class="card-img-top dev-img">
                            {% else %}
                            <img src="http://placekitten.com/300/300" alt="a random kitten photo used as a placeholder picture" class="card-img-top dev-img">
                            {% endif %}
                        </a>
                        <a href="{% url 'app_home:profile-detail-view' dev.pk %}" class="card-title">{{ dev.username }}</a>
                        <p>{% for language in dev.p_language.values %}
                            <img src="{{ language.language_icon.url }}" alt="Small icon representing the programming language {{ language.language }}" class="icon-sm">
                            {% endfor %}
                        </p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>


    <nav aria-label="Page navigation" class="small-margin">
        <ul class="pagination justify-content-center">
            {% if users.has_previous %}
            <li class="page-item"><a class="page-link dark-text" href="?page={{ users.previous_page_number }}{{ href_filter }}">&laquo; Previous</a></li>
            {% else %}
            <li class="page-item"><a class="page-link dark-text disabled" href="#">&laquo; Previous</a></li>
            {% endif %}
            {% for n in p_nums %}
            {% if users.number == forloop.counter %}
            <li class="page-item"><a class="page-link dark-text active">{{ forloop.counter }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link dark-text" href="?page={{ forloop.counter }}{{ href_filter }}">{{ forloop.counter }}</a></li>
            {% endif %}
            {% endfor %}
            
            {% if users.has_next %}
            <li class="page-item"><a class="page-link dark-text" href="?page={{ users.next_page_number }}{{ href_filter }}">Next &raquo;</a></li>
            {% else %}
            <li class="page-item"><a class="page-link dark-text disabled" href="#">Next &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>

    {% else %}
    <div class="row">
        <div class="col-md-12 text-center">
            <p>Please log in or register to see the Developer Overview</p>
            <p><a href="{% url 'app_user:register' %}" class="btn btn-primary">Register</a>
            <a href="/user/login/" class="btn btn-primary">Login</a></p>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

app_home/templates/app_home/edit_project.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Edit Project{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h1>Edit Project</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-warning">Edit Project</button>
                <a href="{% url 'app_home:project-overview' %}" class="btn btn-primary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_home/templates/app_home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 logo-container">
            <img src="https://res.cloudinary.com/djlm3llv5/image/upload/v1677952586/non%20square%20imgs/yydclfgb81lrk8m2hgnt.png" class="main-logo" alt="The Developer Connect logo">
        </div>
    </div>
    
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Welcome, {{user.username}}</h1>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-12 text-center">
            <a href="{% url 'app_user:register' %}" class="btn btn-primary">Register</a>
            <a href="/user/login/" class="btn btn-primary">Login</a>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

app_home/templates/app_home/project_detail_view.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="text-center">{{ project.title }}</h1>
            {% if project.user.values.0.id == user.id %}
            <!-- if the project belongs to the logged in user -->
            <div class="square-container">
                <div class="square-img">
                    {% if project.project_pic.values.0.project_picture %}
                    <!-- link to the add pictures page -->
                    <a href="{% url 'app_home:add-project-pic' project.pk %}">
                        <img src={{project.project_pic.values.0.project_picture.url}} alt="The image for the {{ project.title }} project">
                    </a>
                        {% else %}
                    <a href="{% url 'app_home:add-project-pic' project.pk %}">
                        <img src="https://res.cloudinary.com/djlm3llv5/image/upload/v1678139273/x67igozvm2kkr8srya94.jpg" alt="A placeholder picture inviting the user to upload a project picture">
                    </a>
                </div>
            </div>
            {% endif %}
            {% else %}
            {% if project.project_pic.values.0.project_picture %}
            <!-- if the project does not belong to the logged in user -->
            <div class="square-container">
                <div class="square-img">
                    <img src={{project.project_pic.values.0.project_picture.url}} alt="The image for the {{ project.title }} project">
                </div>
            </div>
            {% else %}
            <div class="square-container">
                <div class="square-img">
                    <img src="https://res.cloudinary.com/djlm3llv5/image/upload/v1678138517/zac9ltpydeu3t6uiabnb.jpg" alt="A placeholder picture to show the project does not have any pictures associated with it">
                </div>
            </div>
            {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 offset-md-2 text-center">
            <p>{{ project.description }}</p>
            {% if project.user.values.0.id %}
            <p><strong>Project Owner: </strong><a href="{% url 'app_home:profile-detail-view' project.user.values.0.id %}">{{ project.user.values.0.username }}</a></p>
            {% else %}
            <p><strong>Project Owner: </strong>This project no longer has an owner</p>
            {% endif %}
            <p><strong>Programming Languages:</strong> 
                {% for language in project.p_language.values %}
                <img src="{{ language.language_icon.url }}" alt="The {{ language.language }} icon" class="icon-sm" title="{{ language.language }}">
                {% endfor %}
            </p>
            <div class="row">
                <div class="col-md-12">
                    {% if project.user.values.0.id == user.id %}
                    <p>
                        <a href="{% url 'app_home:project-edit-view' project.pk %}" class="btn btn-primary small-margin">Edit Project</a>
                        <button type="button" class="btn btn-danger small-margin" data-bs-toggle="modal" data-bs-target="#delete-project-modal">Delete Project</button>
                    </p>
                    {% endif %}
                    <a href="{% url 'app_home:project-overview' %}" class="btn btn-primary small-margin">Back to overview</a>
                    {% if project.user.values and project.user.values.0.id != user.id %}
                    <a href="{% url 'app_user:add_message' project.user.values.0.id %}" class="btn btn-primary small-margin"><i class="fa-regular fa-envelope"></i> Message project owner</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal for delete button -->
<!-- https://getbootstrap.com/docs/5.0/components/modal/ -->
<div class="modal fade" id="delete-project-modal" tabindex="-1" role="dialog" aria-labelledby="deleteProjectModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="deleteProjectModal">Are you sure?</h2>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span id="close-modal-span" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>This action will delete your project and any associated pictures.</p>
                <p>This action is IRREVERSIBLE. Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>
                <a href="{% url 'app_home:delete-project' project.id %}" class="btn btn-danger" id="confirm-delete">Delete my project</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app_home/templates/app_home/user_detail_view.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="text-center">{{ user_for_profile.username }}'s Profile</h1>
            <div class="square-container">
                <div class="square-img">
                        {% if user_for_profile.profile_pic.values %}
                        <img src={{user_for_profile.profile_pic.values.0.profile_picture.url}} alt="{{ user_for_profile.username }}'s profile picture">
                        {% else %}
                        <img src="http://placekitten.com/300/300" alt="A random kitten photo as an image placeholder">
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 offset-md-3">
            {% for key, value in user_for_profile.to_json.items %}
            {% if value and key != 'email' and key != 'username' %}
            <p><strong>{{ key.title }}:</strong> {{ value }}</p>
            {% endif %}
            {% endfor %}
            {% if p_langs %}
            <p><strong>Programming Languages:</strong></p>
            {% for lang in p_langs %}
            <img src="{{ lang.language_icon.url }}" class="icon-sm" alt="{{lang.language}} icon" title="{{ lang.language }}">
            {% endfor %}
            {% endif %}
            {% if user_projects %}
            <p>Projects: 
            {% for project in user_projects %}
                <a href="{% url 'app_home:project-detail-view' project.pk %}">{{project.title}}</a>
            {% endfor %}</p>
            {% endif %}
            <div>
                <a href="{% url 'app_home:developer-overview' %}" class="btn btn-primary margin-above">Back to overview</a>
                <a href="{% url 'app_user:add_message' user_for_profile.pk %}" class="btn btn-primary margin-above"><i class="fa-regular fa-envelope"></i> Send message</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}