app_home/urls.py
from django.urls import path
from . import views

app_name = "app_home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path(
        "developers/",
        views.DeveloperOverview.as_view(),
        name="developer-overview",
    ),
    path(
        "projects/", views.ProjectOverview.as_view(), name="project-overview"
    ),
    path(
        "projects/create/",
        views.CreateProjectView.as_view(),
        name="create-project",
    ),
    path(
        "users/<int:pk>/",
        views.ProfileDetailView.as_view(),
        name="profile-detail-view",
    ),
    path(
        "projects/<int:pk>/",
        views.ProjectDetailView.as_view(),
        name="project-detail-view",
    ),
    path(
        "projects/edit/<int:pk>/",
        views.EditProjectView.as_view(),
        name="project-edit-view",
    ),
    path(
        "projects/delete/<int:pk>/",
        views.DeleteProjectView.as_view(),
        name="delete-project",
    ),
    path(
        "projects/<int:pk>/picture/",
        views.AddProjectPicture.as_view(),
        name="add-project-pic",
    ),
    path(
        "projects/picture/delete/<int:pk>/",
        views.DeleteProjectPicture.as_view(),
        name="delete-project-pic",
    ),
]

app_user/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "app_user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path(
        "profile/edit/", views.EditProfileView.as_view(), name="edit-profile"
    ),
    path(
        "profile/delete/",
        views.DeleteProfileView.as_view(),
        name="delete-profile",
    ),
    path(
        "profile/picture/",
        views.AddProfilePicView.as_view(),
        name="add-profile-pic",
    ),
    path(
        "profile/picture/delete/<int:pk>/",
        views.DeleteProfilePicView.as_view(),
        name="delete-profile-pic",
    ),
    path("messages/", views.Messages.as_view(), name="messages"),
    path("messages/sent/", views.SentMessages.as_view(), name="sent-messages"),
    path(
        "messages/<int:pk>/",
        views.IndividualMsg.as_view(),
        name="individual_msg",
    ),
    path(
        "messages/send/<int:pk>/",
        views.AddMessage.as_view(),
        name="add_message",
    ),
    path(
        "messages/edit/<int:pk>/",
        views.EditMessage.as_view(),
        name="edit_message",
    ),
    path(
        "messages/delete/<int:pk>/",
        views.DeleteMessage.as_view(),
        name="delete_message",
    ),
]

developer_matcher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", include("app_home.urls")),
    path("user/", include("allauth.urls")),
    path("user/", include("app_user.urls")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="https://res.cloudinary.com/djlm3llv5/image/upload/v1677952722/non%20square%20imgs/uh7zvudottb9s7jzsyzr.png">
    <!-- BOOTSTRAP from CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- DEVELOPMENT CSS -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}"> -->
    <!-- PRODUCTION CSS -->
    <link rel="stylesheet" type="text/css" href="https://res.cloudinary.com/djlm3llv5/raw/upload/v1678994964/static-files/hjp3lcnak20xepseey40.css">
    
    <title>{% block title %} Developer Connect {% endblock %}</title>
</head>
<body>
    <div class="min-vh-100 navbar-padding nav-x">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky">
            <div class="container-fluid">
                <a href="{% url 'app_home:index' %}" class="navbar-brand"><img src="https://res.cloudinary.com/djlm3llv5/image/upload/v1677952586/non%20square%20imgs/yydclfgb81lrk8m2hgnt.png" alt="The developer connect logo" style="height: 110px"></a>
                <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item me-2"><a class="nav-link nav-link-text" href="{% url 'app_home:developer-overview' %}">Developer Search</a></li>
                        <li class="nav-item me-2"><a class="nav-link nav-link-text" href="{% url 'app_home:project-overview' %}">Project Search</a></li>
                        <li class="nav-item me-2"><a class="nav-link nav-link-text" href="{% url 'app_home:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item me-2 d-block d-sm-none"><a class="nav-item nav-link" href="{% url 'app_user:profile' %}">My Profile</a></li>
                        <li class="nav-item me-2 d-block d-sm-none"><a class="nav-item nav-link" href="{% url 'app_user:messages' %}">My Messages</a></li>
                        <li class="nav-item me-2 d-block d-sm-none"><a class="nav-link" href="{% url 'account_logout' %}">Log out</a></li>
                        {% else %}
                        <li class="nav-item me-2 d-block d-sm-none"><a class="nav-item nav-link" href="{% url 'app_user:register' %}">Register</a></li>
                        <li class="nav-item me-2 d-block d-sm-none"><a class="nav-item nav-link" href="{% url 'account_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="d-none d-md-flex">
                    {% if user.is_authenticated %}
                    <p class="navbar-text my-auto me-2" style="padding: 20px;">Logged in as {{user.username.title}}</p>
                    <div class="dropdown" style="margin-right: 2em;">
                        <a href="#" data-bs-toggle="dropdown" class="btn dropdown-toggle" style="text-decoration: none;">
                            {% if user.profile_pic.values %}
                            <img style="width: 100px; border-radius: 50%;" src="{{ user.profile_pic.values.0.profile_picture.url }}" alt="Your profile picture"><b class="caret"></b>
                            {% else %}
                            <img style="width: 100px; border-radius: 50%;" src="http://placekitten.com/300/300" alt="A placeholder kitten image">
                            <span class="caret"></span>
                            {% endif %} 
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" style="font-size:120%;">
                            <li><a href="{% url 'app_user:profile' %}" class="dropdown-link">My Profile</a></li>
                            <li><a href="{% url 'app_user:messages' %}" class="dropdown-link">My Messages</a></li>
                            <li><a href="/user/logout/" class="dropdown-link">Log out</a></li>
                        </ul>
                    </div>
                    
                    {% else %}
                    <p class="navbar-text my-auto me-2"><i>Get connected now!</i></p>
                    <div class="navbar">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item me-2"><a class="nav-link" href="/user/login/">Sign In</a></li>
                            <li class="nav-item me-2"><a class="nav-link" href="{% url 'app_user:register' %}">Sign Up</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% if messages %}
        <section>
            {% for msg in messages %}
            <!-- all django message tags mirror bootstrap, except error/danger -->
            <aside class="alert {% if msg.tags == 'error' %}alert-danger{% else %}alert-{{ msg.tags }}{% endif %} text-center alert-dismissible fade show" role="alert">
                <h3>{{ msg }}</h3>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
            </aside>
            {% endfor %}
        </section>
        {% endif %} 

        {% block content %}{% endblock %}

    </div>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 border-top footer-bg" id="footer">
        <ul class="nav col-md-12 justify-content-center list-unstyled d-flex">
            <li class="ms-3"><a href="http://www.instagram.com" target="_blank" rel="noopener" aria-label="Visit our Instagram page (opens in a new tab)" class="text-muted"><i class="fa-brands fa-instagram"></i></a></li>
            <li class="ms-3"><a href="http://www.facebook.com" target="_blank" rel="noopener" aria-label="Visit our Facebook page (opens in a new tab)" class="text-muted"><i class="fa-brands fa-facebook"></i></a></li>
            <li class="ms-3"><a href="http://www.twitter.com" target="_blank" rel="noopener" aria-label="Visit our Twitter page (opens in a new tab)" class="text-muted"><i class="fa-brands fa-twitter"></i></a></li>
            <li class="ms-3"><a href="http://www.github.com" target="_blank" rel="noopener" aria-label="Visit our Github page (opens in a new tab)" class="text-muted"><i class="fa-brands fa-github"></i></a></li>
        </ul>
    </footer>

    <script src="https://kit.fontawesome.com/4a9fb983cf.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

templates/style_404.html
{% extends "base.html" %}
{% block title %}Messages{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <p class="large-error-text">404 Error</p>
            <h2>Oops! Looks like that page doesn't exist!</h2>
            <h3><a href="{% url 'app_home:index' %}"> Click here to get reconnected</a></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 img-404-500-container ">
            <img class="img-404" src="https://res.cloudinary.com/djlm3llv5/image/upload/v1677945220/non%20square%20imgs/hj9v5lng9ftakoydprqc.jpg" alt="Two people trying to reconnect a disconnected plug and socket">
        </div>
    </div>
</div>

{% endblock %}

templates/style_500.html
{% extends "base.html" %}
{% block title %}Messages{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <p class="large-error-text">500 Error</p>
            <h2>Oops! Something went wrong!</h2>
            <h3><a href="{% url 'app_home:index' %}"> Click here to get reconnected</a></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 img-404-500-container ">
            <img class="img-404" src="https://res.cloudinary.com/djlm3llv5/image/upload/v1677948176/non%20square%20imgs/kw8vcyj0mgytgeghyvnp.jpg" alt="A computer with an exclamation point and people trying to fix it">
        </div>
    </div>
</div>

{% endblock %}