app_home/urls.py
from django.urls import path
from . import views

app_name = "app_home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path(
        "developers/",
        views.DeveloperOverview.as_view(),
        name="developer-overview",
    ),
    path(
        "projects/", views.ProjectOverview.as_view(), name="project-overview"
    ),
    path(
        "projects/create/",
        views.CreateProjectView.as_view(),
        name="create-project",
    ),
    path(
        "users/<int:pk>/",
        views.ProfileDetailView.as_view(),
        name="profile-detail-view",
    ),
    path(
        "projects/<int:pk>/",
        views.ProjectDetailView.as_view(),
        name="project-detail-view",
    ),
    path(
        "projects/edit/<int:pk>/",
        views.EditProjectView.as_view(),
        name="project-edit-view",
    ),
    path(
        "projects/delete/<int:pk>/",
        views.DeleteProjectView.as_view(),
        name="delete-project",
    ),
    path(
        "projects/<int:pk>/picture/",
        views.AddProjectPicture.as_view(),
        name="add-project-pic",
    ),
    path(
        "projects/picture/delete/<int:pk>/",
        views.DeleteProjectPicture.as_view(),
        name="delete-project-pic",
    ),
]

app_user/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "app_user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path(
        "profile/edit/", views.EditProfileView.as_view(), name="edit-profile"
    ),
    path(
        "profile/delete/",
        views.DeleteProfileView.as_view(),
        name="delete-profile",
    ),
    path(
        "profile/picture/",
        views.AddProfilePicView.as_view(),
        name="add-profile-pic",
    ),
    path(
        "profile/picture/delete/<int:pk>/",
        views.DeleteProfilePicView.as_view(),
        name="delete-profile-pic",
    ),
    path("messages/", views.Messages.as_view(), name="messages"),
    path("messages/sent/", views.SentMessages.as_view(), name="sent-messages"),
    path(
        "messages/<int:pk>/",
        views.IndividualMsg.as_view(),
        name="individual_msg",
    ),
    path(
        "messages/send/<int:pk>/",
        views.AddMessage.as_view(),
        name="add_message",
    ),
    path(
        "messages/edit/<int:pk>/",
        views.EditMessage.as_view(),
        name="edit_message",
    ),
    path(
        "messages/delete/<int:pk>/",
        views.DeleteMessage.as_view(),
        name="delete_message",
    ),
]

developer_matcher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", include("app_home.urls")),
    path("user/", include("allauth.urls")),
    path("user/", include("app_user.urls")),
]

app_user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import ModelForm, ValidationError
from django_countries.fields import CountryField
from better_profanity import profanity
from .models import User, ProgramLang, UserProfilePicture, Message


def validate_username(data):
    """Checks that a username is not already taken and does not
    contain profanities"""

    if isinstance(data, str):
        username = data
    else:
        username = data.cleaned_data["username"]
        if data.instance:
            # check if username is unchanged
            if data.instance.username == username:
                return

    # Check username for profanity and do not allow if present
    if profanity.contains_profanity(username):
        raise ValidationError("profanity")
    else:
        # Check if username already taken and return error if so
        try:
            taken_username = User.objects.get(username=username)
            raise ValidationError("duplicate_name")
        except User.DoesNotExist:
            return


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(
        help_text="Enter a valid email address", required=True
    )

    class Meta:
        model = get_user_model()
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

    def clean(self):
        validate_username(self)


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "p_language",
            "location",
            "github_username",
            "github_url",
            "linked_in",
            "portfolio",
        ]
        labels = {
            "p_language": "Programming Language(s)",
        }

    def clean(self):
        validate_username(self)


class AddProfilePictureForm(forms.ModelForm):
    class Meta:
        model = UserProfilePicture
        fields = "__all__"
        exclude = ["user"]
        labels = {"profile_picture": "Profile picture"}


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["title", "message"]

    def save(self, msgtype, commit=True):
        message = super(MessageForm, self).save(commit=False)
        if msgtype == "edit":
            message.edited = True
        if commit:
            message.save()
        return message

app_user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView, FormView
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from .models import User, UserProfilePicture, Project, ProgramLang, Message
from .forms import (
    UserRegistrationForm,
    UserEditForm,
    AddProfilePictureForm,
    MessageForm,
)


class RegisterView(TemplateView):
    """
    View for a new user to register on the site.
    """

    model = User
    template_name = "app_user/register.html"

    def get(self, request, *args, **kwargs):
        # if the user is logged in, registration page is not available
        if request.user.is_authenticated:
            return redirect("/")

        registration_form = UserRegistrationForm
        # show user signup page
        return render(
            request,
            "app_user/register.html",
            {
                "registration_form": registration_form,
            },
        )

    def post(self, request, *args, **kwargs):
        registration_form = UserRegistrationForm(request.POST)
        if registration_form.is_valid():
            user = registration_form.save()
            # automatically log the user in following account creation
            login(request, user)
            messages.success(
                request,
                f"Account successfully created. Welcome {user.username}!",
            )
            return redirect(reverse("app_user:profile"))
        elif "profanity" in registration_form.errors.as_text():
            messages.error(
                request, "Please do not use profanities in your username!"
            )
        elif "duplicate_name" in registration_form.errors.as_text():
            messages.error(
                request, "Username already in use! Please choose another"
            )
        else:
            messages.error(
                request, "Form could not be submitted. Please try again."
            )
        return render(
            request,
            "app_user/register.html",
            {
                "registration_form": registration_form,
            },
        )


class ProfileView(LoginRequiredMixin, TemplateView):
    """
    View for user to view their own profile.
    """

    model = User
    template_name = "app_user/user_profile.html"

    def get(self, request):
        user = request.user
        try:
            user_projects = Project.objects.filter(user=user)
        except Exception:
            user_projects = None
        try:
            p_langs = user.p_language.values()
        except Exception:
            p_langs = None
        context = {
            "user": user,
            "p_langs": p_langs,
            "user_projects": user_projects,
        }
        return render(request, "app_user/user_profile.html", context)


class DeleteProfileView(LoginRequiredMixin, TemplateView):
    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)
        user.delete()
        messages.success(request, "Profile successfully deleted!")
        return redirect(reverse("app_home:index"))


class EditProfileView(LoginRequiredMixin, TemplateView):
    """
    View to edit the logged in user's profile
    """

    model = User
    template_name = "app_user/user_profile_edit.html"

    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)
        context = {"form": UserEditForm(instance=user)}

        return render(request, "app_user/user_profile_edit.html", context)

    def post(self, request, *args, **kwargs):
        # get the current user (or return a 404)
        user = get_object_or_404(User, pk=request.user.pk)
        # add data to the form and save it
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile successfully updated!")
            # redirect to main profile page
            return redirect(reverse("app_user:profile"))
        elif "profanity" in form.errors.as_text():
            messages.error(
                request, "Please do not use profanities in your username!"
            )
        elif "duplicate_name" in form.errors.as_text():
            messages.error(
                request, "Username already in use! Please choose another"
            )
        elif not form["p_language"].value():
            messages.error(
                request, "Please select at least one programming language"
            )
        else:
            messages.error(
                request, "Form could not be submitted. Please try again."
            )
        return redirect(reverse("app_user:edit-profile"))


class AddProfilePicView(LoginRequiredMixin, TemplateView):
    """
    View to add or delete a profile picture
    """

    model = User
    template_name = "app_user/profile_pic_edit.html"

    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)
        # get all the pictures for the selected user
        pic_query_set = user.profile_pic.values()
        form = AddProfilePictureForm()
        context = {
            "user": user,
            "pictures": pic_query_set,
            "form": form,
        }

        return render(request, "app_user/profile_pic_edit.html", context)

    def post(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=request.user.pk)
        new_picture = AddProfilePictureForm(
            request.POST, request.FILES, initial={"user": user}
        )
        if new_picture.is_valid():
            new_picture = new_picture.save(commit=False)
            new_picture.user = user
            new_picture.save()
            messages.success(request, "Picture successfully added!")
            return redirect(reverse("app_user:add-profile-pic"))
        else:
            messages.error(
                request, "Picture could not be uploaded. Please try again."
            )
        return redirect(reverse("app_user:add-profile-pic"))


class DeleteProfilePicView(LoginRequiredMixin, TemplateView):
    def get(self, request, *args, **kwargs):
        pic_to_delete = get_object_or_404(UserProfilePicture, pk=kwargs["pk"])
        if request.user == pic_to_delete.user:
            pic_to_delete.delete()
            messages.success(request, "Picture successfully deleted!")
            return redirect(reverse("app_user:add-profile-pic"))
        messages.error(request, "Picture could not be deleted.")
        return redirect("app_home:about")


class Messages(LoginRequiredMixin, TemplateView):
    """
    View of user's received and sent messages
    """

    model = Message
    template_name = "app_user/messages.html"

    def get(self, request):
        received_msgs = Message.objects.filter(user_receiver=request.user)
        # set up pagination for messages (6 per page)
        paginator = Paginator(received_msgs, 6)
        page_number = request.GET.get("page")
        messages = paginator.get_page(page_number)
        p_nums = "p" * messages.paginator.num_pages
        context = {
            "msgs": messages,
            "p_nums": p_nums,
        }
        return render(request, "app_user/messages.html", context)


class SentMessages(LoginRequiredMixin, TemplateView):
    """
    View of user's received and sent messages
    """

    model = Message
    template_name = "app_user/sent_messages.html"

    def get(self, request):
        sent_msgs = Message.objects.filter(user_sender=request.user)
        # set up pagination for messages (6 per page)
        paginator = Paginator(sent_msgs, 6)
        page_number = request.GET.get("page")
        messages = paginator.get_page(page_number)
        p_nums = "p" * messages.paginator.num_pages
        context = {
            "msgs": messages,
            "p_nums": p_nums,
        }
        return render(request, "app_user/sent_msgs.html", context)


class IndividualMsg(LoginRequiredMixin, TemplateView):
    """
    View of a specific selected message
    """

    model = Message
    template_name = "app_user/messages.html"

    def get(self, request, *args, **kwargs):
        message_pk = kwargs["pk"]
        message = Message.objects.get(pk=message_pk)
        if message.user_sender == request.user:
            msg_type = "sent"
        elif message.user_receiver == request.user:
            msg_type = "received"
        else:
            msg_type = "None"
        if msg_type == "sent" or msg_type == "received":
            context = {
                "msg": message,
                "msg_type": msg_type,
            }
            return render(request, "app_user/individual_msg.html", context)
        return redirect(reverse("app_user:messages"))


class AddMessage(LoginRequiredMixin, TemplateView):
    model = Message
    template_name = "app_user:new_message.html"

    def get(self, request, *args, **kwargs):
        form = MessageForm(
            initial={
                "user_sender": request.user,
                "user_receiver": kwargs["pk"],
            }
        )
        context = {
            "sender": request.user,
            "receiver": get_object_or_404(User, pk=kwargs["pk"]),
            "form": form,
        }
        return render(request, "app_user/new_message.html", context)

    def post(self, request, *args, **kwargs):
        new_msg = MessageForm(request.POST)
        if new_msg.is_valid():
            new_msg = new_msg.save("new", commit=False)
            new_msg.user_sender_id = request.POST["sender"]
            new_msg.user_receiver_id = request.POST["receiver"]
            new_msg.save("new")
            messages.success(request, "Message sent!")
        else:
            messages.error(
                request, "Message could not  be sent. Please try again"
            )

app_user/templates/app_user/individual_msg.html
{% extends "base.html" %}
{% block title %}Message{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% if msg_type == "received" %}
            <div class="circle-container">
                <div class="circle-img">
                    <a href="{% url 'app_home:profile-detail-view' msg.user_sender.pk %}">
                        {% if msg.user_sender.profile_pic.values %}
                        <img src={{msg.user_sender.profile_pic.values.0.profile_picture.url}} alt="{{ msg.user_sender.username }}'s profile picture">
                        {% else %}
                        <img src="http://placekitten.com/300/300" alt="A random kitten picture as a placeholder image">
                        {% endif %}
                    </a>
                </div>
            </div>
            <h1 class="text-center">Message from {{ msg.user_sender.username }}</h1>
            <p><strong>Title:</strong> {{ msg.title }}</p>
            <p><strong>Message:</strong> {{ msg.message }}
                {% if msg.edited %} <em class="small-txt">  edited</em> {% endif %}</p>
            <p><strong>Received:</strong> {{ msg.sent_date }}</p>
            <a href="{% url 'app_user:add_message' msg.user_sender.pk %}" class="btn btn-primary small-margin-top"><i class="fa-regular fa-envelope"></i> Reply</a>
            <br>
            {% else %}
            <div class="circle-container">
                <div class="circle-img">
                    <a href="{% url 'app_home:profile-detail-view' msg.user_receiver.pk %}">
                        {% if msg.user_receiver.profile_pic.values %}
                        <img src={{msg.user_receiver.profile_pic.values.0.profile_picture.url}} alt="{{ msg.user_receiver.username }}'s profile picture">
                        {% else %}
                        <img src="http://placekitten.com/300/300" alt="A random kitten picture as a placeholder image">
                        {% endif %}
                    </a>
                </div>
            </div>
            <h1 class="text-center">Your message to <br>{{ msg.user_receiver.username }}</h1>
            <p><strong>Title:</strong> {{ msg.title }}</p>
            <p><strong>Message:</strong> {{ msg.message }}
            {% if msg.edited %} <em class="small-txt">  edited</em> {% endif %}</p>
            <p><strong>Sent:</strong> {{ msg.sent_date }}</p>
            <a href="{% url 'app_user:edit_message' msg.pk %}" class="btn btn-warning small-margin-top">Edit message</a>
            <br>
            {% endif %}
            <a href="{% url 'app_user:messages' %}" class="btn btn-primary small-margin-top">Back to messages</a>
            {% if msg_type == "received" %}
            <a href="{% url 'app_home:profile-detail-view' msg.user_sender.pk %}" class="btn btn-primary small-margin-top">View Profile</a>
            {% else %}
            <a href="{% url 'app_home:profile-detail-view' msg.user_receiver.pk %}" class="btn btn-primary small-margin-top">View Profile</a>
            {% endif %}
            <a href="#" class="btn btn-danger small-margin-top" data-bs-toggle="modal" data-bs-target="#delete-msg-modal">Delete</a>
        </div>
    </div>
</div>

<!-- Modal for delete button -->
<!-- Modified from https://getbootstrap.com/docs/5.0/components/modal/ -->
<div class="modal fade" id="delete-msg-modal" tabindex="-1" role="dialog" aria-labelledby="deleteMsgModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="deleteMsgModal">Are you sure?</h2>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span id="close-modal-span" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>This action will delete your message for both you and the other person.</p>
                <p>This action is IRREVERSIBLE. Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>
                <a href="{% url 'app_user:delete_message' msg.pk %}" class="btn btn-danger" id="confirm-delete">Delete my message</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_user/templates/app_user/messages.html
{% extends "base.html" %}
{% block title %}Messages{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="text-center">Your Inbox</h1>
            <a href="{% url 'app_user:sent-messages' %}" class="btn btn-primary small-margin">Sent Messages</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <h2>Recieved messages:</h2>
            <table class="table">
                <tr>
                    <th class="sm-hidden table-cell-text">Thumbnail</th>
                    <th class="table-cell-text">From</th>
                    <th class="table-cell-text">Title</th>
                    <th class="table-cell-text">Date recieved</th>
                    <th class="table-cell-text sm-hidden">Delete</th>
                </tr>
                {% for msg in msgs %}
                <tr>
                    <td class="align-middle sm-hidden">
                        <div class="square-container-small">
                            <a href="{% url 'app_home:profile-detail-view' msg.user_sender.pk %}" class="square-img">
                                <img src="{{ msg.user_sender.profile_pic.values.0.profile_picture.url }}" alt="{{ msg.user_sender.username }}'s profile picture" class="square-img">
                            </a>
                        </div>
                    </td>
                    <td class="align-middle"><a href="{% url 'app_home:profile-detail-view' msg.user_sender.pk %}" class="table-cell-text">{{ msg.user_sender.username }}</a></td>
                    <td class="align-middle"><a href="{% url 'app_user:individual_msg' msg.pk %}" class="table-cell-text">{{ msg.title }}</a></td>
                    <td class="align-middle small-text">{{ msg.sent_date }}</td>
                    <td class="align-middle"><a class="btn sm-hidden red" data-bs-toggle="modal" data-bs-target="#deleteMsgModal-{{ msg.id }}"><i class="fa-solid fa-trash-can"></i></a>
                        <!-- Modal for delete message button -->
                        <!-- Modified from https://getbootstrap.com/docs/5.0/components/modal/ -->
                        <div class="modal fade" id="deleteMsgModal-{{ msg.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteMsgModalLabel-{{ msg.id }}" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h2 class="modal-title" id="deleteMsgModalLabel-{{ msg.id }}">Are you sure?</h2>
                                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                            <span id="close-pic-modal-span-{{ msg.id }}" aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>This action will delete the message for both you and the other user!</p>
                                        <p>This action is IRREVERSIBLE. Are you sure?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="" class="btn btn-primary" data-bs-dismiss="modal">Cancel</a>
                                        <a href="{% url 'app_user:delete_message' msg.id %}" class="btn btn-danger" id="confirm-pic-delete-{{ msg.id }}">Delete Message</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </table>
            <!-- Pagination -->
            <nav aria-label="Page navigation" class="small-margin">
                <ul class="pagination justify-content-center">
                    {% if msgs.has_previous %}
                    <li class="page-item"><a class="page-link dark-text" href="?page={{ msgs.previous_page_number }}">&laquo; Previous</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link dark-text disabled" href="#">&laquo; Previous</a></li>
                    {% endif %}
                    {% for n in p_nums %}
                    {% if msgs.number == forloop.counter %}
                    <li class="page-item"><a class="page-link dark-text active">{{ forloop.counter }}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link dark-text" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                    {% endif %}
                    {% endfor %}
                    
                    {% if msgs.has_next %}
                    <li class="page-item"><a class="page-link dark-text" href="?page={{ msgs.next_page_number }}">Next &raquo;</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link dark-text disabled" href="#">Next &raquo;</a></li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    </div>
</div>

{% endblock %}

app_user/templates/app_user/sent_msgs.html
{% extends "base.html" %}
{% block title %}Messages{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="text-center">Your Sent Messages</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <a href="{% url 'app_user:messages' %}" class="btn btn-primary small-margin">Received Messages</a>
            <h2>Sent messages:</h2>
            <table class="table">
                <tr>
                    <th class="table-cell-text sm-hidden">Thumbnail</th>
                    <th class="table-cell-text">To</th>
                    <th class="table-cell-text">Title</th>
                    <th class="table-cell-text">Date sent</th>
                    <th class="table-cell-text sm-hidden">Edit</th>
                    <th class="table-cell-text sm-hidden">Delete</th>
                </tr>
                {% for msg in msgs %}
                <tr>
                    <td class="align-middle sm-hidden">
                        <div class="square-container-small">
                            <a href="{% url 'app_home:profile-detail-view' msg.user_receiver.pk %}">
                                <img src="{{ msg.user_receiver.profile_pic.values.0.profile_picture.url }}" alt="{{ msg.user_receiver.username }}'s profile picture" class="square-img">
                            </a>
                        </div>
                    </td>
                    <td class="align-middle"><a href="{% url 'app_home:profile-detail-view' msg.user_receiver.pk %}" class="table-cell-text">{{ msg.user_receiver.username }}</a></td>
                    <td class="align-middle"><a href="{% url 'app_user:individual_msg' msg.pk %}" class="table-cell-text">{{ msg.title }}</a></td>
                    <td class="align-middle small-text">{{ msg.sent_date }}</td>
                    <td class="align-middle"><a href="{% url 'app_user:edit_message' msg.pk %}" class="btn sm-hidden">... <i class="fa-solid fa-pencil"></i></a></td>
                    <td class="align-middle"><a class="btn sm-hidden red" data-bs-toggle="modal" data-bs-target="#deleteMsgModal-{{ msg.id }}"><i class="fa-solid fa-trash-can"></i></a>
                        <!-- Modal for delete message button -->
                        <!-- Modified from https://getbootstrap.com/docs/5.0/components/modal/ -->
                        <div class="modal fade" id="deleteMsgModal-{{ msg.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteMsgModalLabel-{{ msg.id }}" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h2 class="modal-title" id="deleteMsgModalLabel-{{ msg.id }}">Are you sure?</h2>
                                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                            <span id="close-pic-modal-span-{{ msg.id }}" aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>This action will delete the message for both you and the other user!</p>
                                        <p>This action is IRREVERSIBLE. Are you sure?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="#" class="btn btn-primary" data-bs-dismiss="modal">Cancel</a>
                                    <a href="{% url 'app_user:delete_message' msg.id %}" class="btn btn-danger" id="confirm-pic-delete-{{ msg.id }}">Delete Message</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </table>

            <!-- Pagination -->
            <nav aria-label="Page navigation" class="small-margin">
                <ul class="pagination justify-content-center">
                    {% if msgs.has_previous %}
                    <li class="page-item"><a class="page-link dark-text" href="?page={{ msgs.previous_page_number }}">&laquo; Previous</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link dark-text disabled" href="#">&laquo; Previous</a></li>
                    {% endif %}
                    {% for n in p_nums %}
                    {% if msgs.number == forloop.counter %}
                    <li class="page-item"><a class="page-link dark-text active">{{ forloop.counter }}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link dark-text" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                    {% endif %}
                    {% endfor %}
                    
                    {% if msgs.has_next %}
                    <li class="page-item"><a class="page-link dark-text" href="?page={{ msgs.next_page_number }}">Next &raquo;</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link dark-text disabled" href="#">Next &raquo;</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>

{% endblock %}

app_user/templates/app_user/signup.html
{% extends "base.html" %}
{% block title %}Sign up!{% endblock %}

{% block content %}
<form action="" method="POST">
{% csrf_token %}
{{ signup_form.as_p }}
<button type="submit">Sign up</button>
</form>
{% endblock %}

app_user/templates/app_user/success.html
{% extends "base.html" %}
{% block title %}Sign up!{% endblock %}

{% block content %}
<h1>Log in successful!</h1>
{% endblock %}